apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab5-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab5-db
  template:
    metadata:
      labels:
        app: lab5-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lab5-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab5-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: lab5-config
                  key: DB_NAME
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: lab5-pvc
